// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/main.go

package reset_test

import "time"

func (s *ComplexTypesReset) Reset() {
	if s == nil {
		return
	}

	if s.PIntSlice != nil {
		*s.PIntSlice = (*s.PIntSlice)[:0]
	}
	if s.PStrSlice != nil {
		*s.PStrSlice = (*s.PStrSlice)[:0]
	}
	if s.PStrMap != nil {
		clear(*s.PStrMap)
	}
	if s.PIntMap != nil {
		clear(*s.PIntMap)
	}
}

func (s *FullReset) Reset() {
	if s == nil {
		return
	}

	s.IntVal = 0
	s.Int8Val = 0
	s.Int16Val = 0
	s.Int32Val = 0
	s.Int64Val = 0
	s.UintVal = 0
	s.Uint8Val = 0
	s.Uint16Val = 0
	s.Uint32Val = 0
	s.Uint64Val = 0
	s.Float32Val = 0
	s.Float64Val = 0
	s.StringVal = ""
	s.BoolVal = false
	s.ByteVal = 0
	s.RuneVal = 0
	s.TimeVal = *new(time.Time)
}

func (s *NestedReset) Reset() {
	if s == nil {
		return
	}

	s.Simple.Reset()
	if s.Child != nil {
		s.Child.Reset()
	}
}

func (s *OuterWithInnerGeneric) Reset() {
	if s == nil {
		return
	}

	// WARNING: embedded field name could not be resolved for type Bar[int] inside s.Inner
	s.Inner.X = 0
	s.Y = ""
}

func (s *PointersReset) Reset() {
	if s == nil {
		return
	}

	if s.IntPtr != nil {
		*s.IntPtr = 0
	}
	if s.StringPtr != nil {
		*s.StringPtr = ""
	}
	if s.BoolPtr != nil {
		*s.BoolPtr = false
	}
	if s.FloatPtr != nil {
		*s.FloatPtr = 0
	}
}

func (s *SlicesMapReset) Reset() {
	if s == nil {
		return
	}

	s.IntSlice = s.IntSlice[:0]
	s.StrSlice = s.StrSlice[:0]
	clear(s.StrMap)
	clear(s.IntMap)
}

func (s *SomeStruct) Reset() {
	if s == nil {
		return
	}

	s.X = 0
	s.Y = ""
}

func (s *WithEmbedded) Reset() {
	if s == nil {
		return
	}

	s.SomeStruct.Reset()
	if s.FullReset != nil {
		s.FullReset.Reset()
	}
	clear(s.StrMap)
	s.Ints = s.Ints[:0]
}

func (s *WithGenericEmbedded) Reset() {
	if s == nil {
		return
	}

	// WARNING: embedded field name could not be resolved for type Bar[int]
	s.Name = ""
}
